version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
  api:
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - db
